name: Analyze and Test
on: [push, pull_request]
jobs:
  Analyze-and-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Flutter SDK Cache
        id: flutter-sdk
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/flutter
          key: flutter-sdk
      - name: Install flutter SDK    
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Cache flutter
        uses: actions/cache@v2
        with:
          key: flutter-cache
          path: |
            .dart_tool
            build
            ${{env.PUB_CACHE}}
      - name: Flutter Analyze 
        run: flutter analyze
      - name: Flutter test
        run: flutter test --coverage
      - name: Upload to codecov
        run: | 
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t ${CODECOV_TOKEN}
