name: Build Debug
on:
  workflow_dispatch: 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Flutter SDK Cache
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/flutter
          key: flutter-sdk-build-debug
      - name: Install flutter SDK    
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Cache flutter
        uses: actions/cache@v2
        with:
          key: flutter-cache-build-debug
          path: |
            .dart_tool
            build
            ${{env.PUB_CACHE}}
      - name: Build fat APK file
        run: flutter build apk --debug
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: fat APK file
          path: build/app/outputs/flutter-apk/app-debug.apk
