name: Upload docs
on: [workflow_dispatch]
jobs:
  buld_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Flutter SDK Cache
        id: flutter-sdk
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/flutter
          key: flutter-sdk
      - name: Install flutter SDK    
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Cache flutter
        uses: actions/cache@v2
        with:
          key: flutter-cache
          path: |
            .dart_tool
            build
            ${{env.PUB_CACHE}}
      - run: flutter pub global activate dartdoc
      - run: dartdoc
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: doc/api
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
