name: Upload docs
on: [workflow_dispatch]
jobs:
  buld_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter pub global activate dartdoc
      - run: dartdoc
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: doc/api
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
